spring:
  application:
    name: springboot-essentials
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/anime?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root

#server:
#error:
#  include-stacktrace:on_param
#
#spring:
#datasource:
#  url:jdbc:mysql//localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#  username:root
#  password:root
#jpa:
#hibernate:
#  ddl-auto:update